baseurl = "/"
languageCode = "en-us"
title = "tf datalab"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/tfausten/tfdatalab"

[params]
    description = "A blog on intellectual property statistics and other data analyses in R"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github" #"atom-one-dark" #"zenburn" #"rainbow" #"tomorrow-night-eighties" #"github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logotf.png"
    width = 50
    height = 50
    alt = "Logo"

